### ISSUE TITLE
(URGENT) Private GitHub repositories should not show "deploy" step as failed (because GH Pages is not available)

### ISSUE THREAD

**Issue by ronaldtse** [actions-mn/build-and-publish#11]
Private GitHub Pages is available for the Enterprise plan, so plans for non-profit or others do not have it.

In these cases, deployment to Pages for a private repository will fail.

This action somehow currently fails for a private repository when Pages is not available / enabled.

This task is to fix this.

e.g.
https://github.com/metanorma/annotated-express-report/actions/runs/7836331958

**Comment by CAMOBAP** [comment]
Unfortunately we cannot handle this in scope of `actions-mn/build-and-publish` or `actions-mn/deploy-pages` actions, because there is no equivalent of `return` action that may finish job gracefully it must fail in this case

To me solution is obvious for private repository there should not be deploy job at all, `build-and-publish` will do it's job and simply publish artifact and that's it

https://github.com/metanorma/annotated-express-report/pull/11

**Comment by ronaldtse** [comment]
@CAMOBAP can you add a note in this action's README that if it's a private repo that does not have GitHub Pages, then do not use the `deploy` step? (and provide a full example for copy/paste) Thanks!
